# Notebook error analysis 

## Refining error types


use OPTICS with GloVe on value errors


## 1. nbs from github - the stack dedup

https://huggingface.co/datasets/bigcode/the-stack-dedup/tree/main/data/jupyter-notebook

### 1.1 Clustering Value errors
Already clustered during the method selection process, now just load the result and choose the best one (optics with word2vec/glove)

In [13]:
# read in all errors from the file
import pandas as pd
import numpy as np 
import cluster_util

path = r"C:\Users\yirwa29\Downloads\Dataset-Nb\nbdata_g_error\analysis_gerr/cluster_selection_g_valueerror"
path_file = path+"/nberror_g_cluster_valueerror.xlsx"

df2_err_valueerr_clusters = pd.read_excel(path_file)
df2_err_valueerr_clusters = df2_err_valueerr_clusters[['fname','evalue','traceback','lib','cluster_optics_glove']]
df2_err_valueerr_clusters.head()

,fname,ename,evalue,evalue_tokenized,traceback,lib
0,00000-101-cookie-clicker-v2-checkpoint.ipynb,keyboardinterrupt,NaN,NaN,['--------------------------------------------...,"urllib3,selenium"
1,00000-1012-demand-forecasting-data-prep-from-s...,operationalerror,"FATAL: no pg_hba.conf entry for host ""75.166....",fatal no entry for host user database pos...,['--------------------------------------------...,psycopg2
2,00000-1017-heatmapseq2seq.ipynb,valueerror,"x and y must have same first dimension, but ha...",x and y must have same first dimension but hav...,['--------------------------------------------...,matplotlib
3,00000-1023-crawler-20190515-20190516.ipynb,connectionerror,HTTPSConnectionPool(host='www.backpackers.com....,httpsconnectionpool hostwwwbackpackerscomtw ma...,['--------------------------------------------...,"requests,urllib3"
4,00000-1033-peer-solution-predicting-survival-t...,urlerror,<urlopen error [Errno 11001] getaddrinfo failed>,urlopen error errno getaddrinfo failed,['--------------------------------------------...,pandas

In [5]:
path_value_err = path+'/cluster_g_valueerror/'
df2_err_valueerr_clusters.to_excel(path_value_err+'cluster_res.xlsx', index=False, engine='xlsxwriter')

Sort the clustering result of the name errors

In [7]:
# save sorted clusters
df2_err_valueerr_clusters.loc[df2_err_valueerr_clusters['cluster_optics_glove']!=-1].sort_values('cluster_optics_glove').to_excel(path_value_err+'cluster_res_sorted.xlsx', index=False, engine='xlsxwriter')
# save only noise samples
df2_err_valueerr_clusters.loc[df2_err_valueerr_clusters['cluster_optics_glove']==-1].sort_values('cluster_optics_glove').to_excel(path_value_err+'cluster_res_noise.xlsx', index=False, engine='xlsxwriter')

Load all the unclustered samples (clustered as noise) of the name errors

try to cluster them again

In [8]:
import pandas as pd

path = r"C:\Users\yirwa29\Downloads\Dataset-Nb\nbdata_g_error\analysis_gerr/cluster_selection_g_valueerror"
path_value_err = path+'/cluster_g_valueerror/'
df2_err_valueerr_clusters_noise = pd.read_excel(path_value_err+'cluster_res_noise.xlsx')

In [9]:
df2_err_valueerr_clusters_noise

,fname,evalue,traceback,lib,cluster_optics_glove
0,00000-155-session10-notes.ipynb,Field names cannot start with an underscore: '...,['--------------------------------------------...,NaN,-1
1,00208-2065-filteralgorithm.ipynb,bessel does not have order selection. Use iirf...,['--------------------------------------------...,scipy,-1
2,00208-2065-filteralgorithm.ipynb,The length of the input vector x must be at le...,['--------------------------------------------...,scipy,-1
3,00208-2065-filteralgorithm.ipynb,Denominator polynomial must be rank-1 array.,['--------------------------------------------...,scipy,-1
4,00208-1997-python-data-science-01.ipynb,could not convert string to float: 'Q',['--------------------------------------------...,sklearn,-1
...,...,...,...,...,...
8105,00105-1178-execmunsup1.ipynb,Argument U has a size 4 which does not match 1...,['--------------------------------------------...,matplotlib,-1
8106,00105-1071-untitled.ipynb,A value in x_new is below the interpolation ra...,['--------------------------------------------...,scipy,-1
8107,00104-998-titanic-checkpoint.ipynb,could not convert string to float: 'Q',['--------------------------------------------...,sklearn,-1
8108,00105-1878-ch09-sec02-2-balancedtruncation.ipynb,"Oops, the system is unstable!",['--------------------------------------------...,control,-1
8109,00311-984-working-with-mask-during-horizontal-...,Input matrix must have some non-missing values,['--------------------------------------------...,fancyimpute,-1

In [ ]:
# recluster using optics (with a higher variance?)

#### NameError, evalue

In [6]:
df2_err_ename = df2_err[df2_err['ename']=='nameerror']
err_descs = df2_err_ename['evalue'].values.astype('U') # traceback: memory error

In [ ]:
num_clusters = 2
_, res, _ = cluster_util.cluster_kmeans(input_texts=err_descs, n_clusters=num_clusters) # km_model, res, vectorized_descs
# plot the results 
# cluster_util.plot_clusters(vectorized_descs, num_clusters, km_model.labels_)

In [7]:
cluster_util.print_clusters(num_clusters, res)

cluster 0 has 50 samples
                              errdesc  cluster
36857     name 'error' is not defined        0
30187     name 'error' is not defined        0
166       name 'error' is not defined        0
17326     name 'error' is not defined        0
694       name 'error' is not defined        0
1979      name 'error' is not defined        0
32475     name 'error' is not defined        0
34312     name 'error' is not defined        0
31205  This is the raised name error.        0
25804     name 'error' is not defined        0


cluster 1 has 36955 samples
                                   errdesc  cluster
7019              name 'df' is not defined        1
31697           name 'tmax' is not defined        1
20632            name 'nlp' is not defined        1
10551             name 'np' is not defined        1
35938             name 'bb' is not defined        1
11316          name 'model' is not defined        1
23866           name 'set1' is not defined        1
5088             name 'plt' is not defined        1
29311     name 'SqlService' is not defined        1
27845  name 'obj_a_aspects' is not defined        1

##### Note:

found **ignored** values in evalue column in a cluster, but they seem have evalue in traceback. I extracted those and retried.

##### No obvious clusters found in NameError.

#### TypeError, evalue

In [16]:
df2_err_ename = df2_err[df2_err['ename']=='typeerror']
err_descs = df2_err_ename['evalue'].values.astype('U') # traceback: memory error

In [17]:
num_clusters = 10
_, res, _ = cluster_util.cluster_kmeans(input_texts=err_descs, n_clusters=num_clusters, max_iter=1000)
# plot the results 
# cluster_util.plot_clusters(vectorized_descs, num_clusters, km_model.labels_)
cluster_util.print_clusters(num_clusters, res)

cluster 0 has 1488 samples
                                             errdesc  cluster
11659    can only concatenate str (not "int") to str        0
8625                    'int' object is not iterable        0
4428                    'str' object is not callable        0
12026    can only concatenate str (not "int") to str        0
21289    can only concatenate str (not "int") to str        0
6557           cannot unpack non-iterable int object        0
14131                   'str' object is not callable        0
9622                            must be str, not int        0
9063     can only concatenate str (not "int") to str        0
16412  can only concatenate str (not "float") to str        0


cluster 1 has 2519 samples
                                                 errdesc  cluster
18588  emptyFunction() takes 0 positional arguments b...        1
20039  field() takes 0 positional arguments but 1 was...        1
1419   emptyFunction() takes 0 positional arguments b...        1
3752   emptyFunction() takes 0 positional arguments b...        1
3308   emptyFunction() takes 0 positional arguments b...        1
1512   emptyFunction() takes 0 positional arguments b...        1
3525   emptyFunction() takes 0 positional arguments b...        1
3748   emptyFunction() takes 0 positional arguments b...        1
5311   emptyFunction() takes 0 positional arguments b...        1
5024   emptyFunction() takes 0 positional arguments b...        1


cluster 2 has 3008 samples
                                       errdesc  cluster
16035     object of type 'Sample' has no len()        2
6764            'tuple' object is not callable        2
6350            'Human' object is not callable        2
22486        object of type 'int' has no len()        2
18095  'generator' object is not subscriptable        2
21724            'dict' object is not callable        2
1964    'NoneType' object is not subscriptable        2
13224        object of type 'int' has no len()        2
10881        'NoneType' object is not callable        2
21954       'DataFrame' object is not callable        2


cluster 3 has 1944 samples
                                               errdesc  cluster
6338   'tuple' object does not support item assignment        3
4682   'tuple' object does not support item assignment        3
15872    'str' object does not support item assignment        3
12859    'tuple' object does not support item deletion        3
5968   'tuple' object does not support item assignment        3
1836   'tuple' object does not support item assignment        3
9164   'tuple' object does not support item assignment        3
17380  'tuple' object does not support item assignment        3
8144     'str' object does not support item assignment        3
22     'tuple' object does not support item assignment        3


cluster 4 has 9320 samples
                                                 errdesc  cluster
11204  __init__() got an unexpected keyword argument ...        4
18967  f() missing 1 required positional argument: '_ps'        4
18096       strftime() argument 1 must be str, not tuple        4
17388  make_csv_dataset_v2() got an unexpected keywor...        4
1778                      new(): invalid data type 'str'        4
22079  plot_e() missing 1 required positional argumen...        4
16379                 reload() argument must be a module        4
5519                array([1.]) is not JSON serializable        4
12362  discriminator() got an unexpected keyword argu...        4
10953  cannot insert an item into a CategoricalIndex ...        4


cluster 5 has 612 samples
                                                 errdesc  cluster
17472  list indices must be integers or slices, not L...        5
2245   list indices must be integers or slices, not t...        5
2776                     Vector indices must be integers        5
22322  list indices must be integers or slices, not t...        5
2768    list indices must be integers or slices, not str        5
9082   list indices must be integers or slices, not t...        5
12324   list indices must be integers or slices, not str        5
19362                    string indices must be integers        5
9252   slice indices must be integers or None or have...        5
7054                     string indices must be integers        5


cluster 6 has 1199 samples
                                                 errdesc  cluster
10839                      'list' object is not callable        6
528        can only concatenate list (not "int") to list        6
11078                   unhashable type: 'numpy.ndarray'        6
11097                            unhashable type: 'list'        6
7296                             unhashable type: 'list'        6
1748       can only concatenate list (not "str") to list        6
18889      can only concatenate list (not "int") to list        6
17307      can only concatenate list (not "int") to list        6
23394                            unhashable type: 'list'        6
18277  unsupported operand type(s) for divmod(): 'lis...        6


cluster 7 has 1701 samples
                                                 errdesc  cluster
8668   unsupported operand type(s) for *: 'int' and '...        7
21976  unsupported operand type(s) for &: 'float' and...        7
21714  unsupported operand type(s) for +: 'dict' and ...        7
12697  unsupported operand type(s) for +: 'int' and '...        7
5554   unsupported operand type(s) for -: 'str' and '...        7
23533  unsupported operand type(s) for /: 'str' and '...        7
17011  unsupported operand type(s) for -: 'float' and...        7
12920  unsupported operand type(s) for +: 'int' and '...        7
3964   unsupported operand type(s) for +: 'int' and '...        7
22724  unsupported operand type(s) for ** or pow(): '...        7


cluster 8 has 1098 samples
                                                 errdesc  cluster
14976                object of type 'float' has no len()        8
15210  Image data of dtype object cannot be converted...        8
9936   'float' object cannot be interpreted as an int...        8
11817  'Tensor' object cannot be interpreted as an in...        8
7690   only integer scalar arrays can be converted to...        8
260    __init__(): incompatible constructor arguments...        8
15175                     'float' object is not iterable        8
8503               bad operand type for unary ~: 'float'        8
5490                      'float' object is not callable        8
4262                                 a float is required        8


cluster 9 has 730 samples
                                                 errdesc  cluster
13451  '>' not supported between instances of 'str' a...        9
21527  '>' not supported between instances of 'list' ...        9
12912  '<' not supported between instances of 'int' a...        9
23278  ufunc 'isnan' not supported for the input type...        9
9341   '>' not supported between instances of 'NoneTy...        9
16225  '<' not supported between instances of 'str' a...        9
6175   '<' not supported between instances of 'int' a...        9
8358   '<' not supported between instances of 'float'...        9
17272  '<' not supported between instances of 'str' a...        9
19436  '<' not supported between instances of 'tuple'...        9

##### Note:

10 clusters for TypeError:

    1. can only concatenate *something* to str
    2. *something* missing *somenumber* required positional arguments...
    3. *something* object is not callable/iterable/has no len()
    4. *something* object does not support item assignment
    5. others
    6. list/tuple indices must be integers or slices, not str
    7. unhashable type: 'list/dict/slice', can only concatenate list (not "int") to list
    8. unsupported operand type(s) for -: 'str' and '..
    9. *something* object cannot be interpreted/converted...
    10. '<' not supported between instances of 'str' a..

#### AttributeError, evalue

In [23]:
df2_err_ename = df2_err[df2_err['ename']=='attributeerror']
err_descs = df2_err_ename['evalue'].values.astype('U')

In [24]:
num_clusters = 2
_, res, _ = cluster_util.cluster_kmeans(input_texts=err_descs, n_clusters=num_clusters, max_iter=500)
cluster_util.print_clusters(num_clusters, res)

cluster 0 has 855 samples
                                                 errdesc  cluster
12354         'DataFrame' object has no attribute 'Date'        0
2388           'DataFrame' object has no attribute 'get'        0
11488     'DataFrame' object has no attribute 'pred_sgd'        0
5408            'DataFrame' object has no attribute 'ix'        0
2060        'DataFrame' object has no attribute 'unique'        0
12927          'DataFrame' object has no attribute 'str'        0
1511          'DataFrame' object has no attribute 'prob'        0
1765   'DataFrame' object has no attribute 'fivegram_...        0
5366           'DataFrame' object has no attribute 'hit'        0
12886       'DataFrame' object has no attribute 'equity'        0


cluster 1 has 12076 samples
                                                 errdesc  cluster
6759           'Person' object has no attribute '__name'        1
7564         module 'numpy' has no attribute 'heaviside'        1
4495                                              dtypes        1
4144          'NoneType' object has no attribute 'split'        1
4641            'tuple' object has no attribute 'append'        1
12101               'zip' object has no attribute 'sort'        1
10725             'str' object has no attribute 'append'        1
11184  module 'tensorflow' has no attribute 'reset_de...        1
7764             module 'seaborn' has no attribute 'plt'        1
10862  Layer dense_28 is not connected, no input to r...        1

##### Note: No obvious clusters in AttributeError

#### SyntaxError, evalue

In [25]:
df2_err_ename = df2_err[df2_err['ename']=='syntaxerror']
err_descs = df2_err_ename['evalue'].values.astype('U')

In [27]:
num_clusters = 10
_, res, _ = cluster_util.cluster_kmeans(input_texts=err_descs, n_clusters=num_clusters, max_iter=500)
cluster_util.print_clusters(num_clusters, res)

cluster 0 has 77 samples
                                                errdesc  cluster
9201  keyword can't be an expression (<ipython-input...        0
7244  f-string expression part cannot include a back...        0
2900  keyword can't be an expression (<ipython-input...        0
6632  keyword can't be an expression (<ipython-input...        0
2495  keyword can't be an expression (<ipython-input...        0
7260  can't use starred expression here (<ipython-in...        0
6006  keyword can't be an expression (<ipython-input...        0
7055  can't use starred expression here (<ipython-in...        0
1262  keyword can't be an expression (<ipython-input...        0
461   keyword can't be an expression (<ipython-input...        0


cluster 1 has 58 samples
                                                errdesc  cluster
8337  invalid syntax (<ipython-input-35-fba0d58980c0...        1
7267  'return' outside function (<ipython-input-8-6e...        1
951   invalid syntax (<ipython-input-35-85431d43a0b1...        1
2893  invalid syntax (<ipython-input-17-bf0cee6fee9b...        1
8177  invalid syntax (<ipython-input-35-c1e503f4d84e...        1
3295  invalid syntax (<ipython-input-35-5961066ef753...        1
1821  invalid syntax (<ipython-input-35-e27c1f060d6c...        1
1228  invalid syntax (<ipython-input-35-e48f2dfcfac3...        1
6160  invalid syntax (<ipython-input-35-8beafa51d833...        1
7673  invalid syntax (<ipython-input-35-1b65b7d2966e...        1


cluster 2 has 655 samples
                                                errdesc  cluster
2187  unexpected EOF while parsing (<ipython-input-4...        2
9563  unexpected EOF while parsing (<ipython-input-1...        2
801   unexpected EOF while parsing (<ipython-input-3...        2
1286                      unexpected EOF while parsing'        2
4373  unexpected EOF while parsing (<ipython-input-6...        2
6077  unexpected EOF while parsing (<ipython-input-4...        2
5912                      unexpected EOF while parsing'        2
4345  unexpected EOF while parsing (<ipython-input-7...        2
5973  unexpected EOF while parsing (<ipython-input-5...        2
6589  unexpected EOF while parsing (<ipython-input-1...        2


cluster 3 has 297 samples
                                                errdesc  cluster
7887  Missing parentheses in call to 'print'. Did yo...        3
6785  Missing parentheses in call to 'print'. Did yo...        3
8370  Missing parentheses in call to 'print' (<ipyth...        3
5746  Missing parentheses in call to 'print' (__init...        3
5611  Missing parentheses in call to 'print'. Did yo...        3
2431  Missing parentheses in call to 'print' (<ipyth...        3
7763  Missing parentheses in call to 'print'. Did yo...        3
2822  Missing parentheses in call to 'print'. Did yo...        3
6393  Missing parentheses in call to 'print'. Did yo...        3
8958  Missing parentheses in call to 'print' (<ipyth...        3


cluster 4 has 356 samples
                                                errdesc  cluster
3991  positional argument follows keyword argument (...        4
2856  positional argument follows keyword argument (...        4
8081  positional argument follows keyword argument (...        4
6443  non-default argument follows default argument ...        4
895   non-default argument follows default argument ...        4
8059  positional argument follows keyword argument (...        4
4133  positional argument follows keyword argument (...        4
8369  positional argument follows keyword argument (...        4
6899  positional argument follows keyword argument (...        4
9528  non-default argument follows default argument ...        4


cluster 5 has 1255 samples
                                                errdesc  cluster
1547  (unicode error) 'unicodeescape' codec can't de...        5
4798  'return' outside function (<ipython-input-44-d...        5
9470  illegal target for annotation (<ipython-input-...        5
8078  leading zeros in decimal integer literals are ...        5
4495           invalid syntax (diagnostics.py, line 94)        5
5289  invalid syntax (Temp/ipykernel_20148/266543758...        5
7437                         can\'t assign to operator'        5
2878  keyword argument repeated: q (921167105.py, li...        5
8878             invalid syntax (3085325471.py, line 4)        5
360               invalid syntax (268261688.py, line 1)        5


cluster 6 has 6407 samples
                                                errdesc  cluster
1875  invalid syntax (<ipython-input-13-f658a6e5037e...        6
1364  invalid syntax (<ipython-input-4-8d5a5acc5edb>...        6
1399  invalid syntax (<ipython-input-3-fca0d63c6f9b>...        6
8371  invalid syntax (<ipython-input-7-c99a8d99a836>...        6
5359  invalid syntax (<ipython-input-5-7577dbe278d1>...        6
7576  invalid syntax (<ipython-input-28-ff9ca35f0873...        6
6518  invalid syntax (<ipython-input-38-9b5f703319a5...        6
9329                                    invalid syntax'        6
4397  invalid syntax (<ipython-input-7-03c5240c9202>...        6
5442  invalid syntax (<ipython-input-10-cb5803a2c56e...        6


cluster 7 has 243 samples
                                                errdesc  cluster
198                    invalid character in identifier'        7
7757  invalid character in identifier (<ipython-inpu...        7
2321  invalid character in identifier (<string>, lin...        7
1257           Identifier 'a' has already been declared        7
1320  unexpected character after line continuation c...        7
3137  invalid character in identifier (<ipython-inpu...        7
8527  unexpected character after line continuation c...        7
1665  invalid character in identifier (<ipython-inpu...        7
2976                   invalid character in identifier'        7
5970  invalid character in identifier (<ipython-inpu...        7


cluster 8 has 436 samples
                                                errdesc  cluster
1953  EOL while scanning string literal (<ipython-in...        8
9460                 EOL while scanning string literal'        8
7799  EOL while scanning string literal (<ipython-in...        8
2709  EOL while scanning string literal (4059993992....        8
1762                 EOL while scanning string literal'        8
1444  EOL while scanning string literal (<ipython-in...        8
6148  EOL while scanning string literal (<ipython-in...        8
6474                  invalid syntax (<string>, line 1)        8
5349  EOL while scanning string literal (<ipython-in...        8
6531                 EOL while scanning string literal'        8


cluster 9 has 152 samples
                                                errdesc  cluster
2134  invalid syntax (<ipython-input-16-0a7c695852a5...        9
3313  invalid syntax (<ipython-input-16-bd54a963cd6e...        9
5346  invalid syntax (<ipython-input-16-efa7122616ce...        9
3405  invalid syntax (<ipython-input-16-2fce13ee096c...        9
1855  invalid syntax (<ipython-input-21-3c323e99d79f...        9
9857  invalid syntax (<ipython-input-16-5fa16817f248...        9
6634  invalid syntax (<ipython-input-16-8521e80609aa...        9
147   invalid syntax (<ipython-input-16-5f4360a3af1e...        9
4024  invalid syntax (<ipython-input-16-eb132473e491...        9
1697  invalid syntax (<ipython-input-16-9315f15ff27b...        9

#### Some mixed error types, evalue

In [28]:
df2_err_ename = df2_err[df2_err['ename']=="error"]
err_descs = df2_err_ename['evalue'].values.astype('U')

In [35]:
num_clusters = 7
_, res, _ = cluster_util.cluster_kmeans(input_texts=err_descs, n_clusters=num_clusters, max_iter=800)
cluster_util.print_clusters(num_clusters, res)

cluster 0 has 220 samples
                                                errdesc  cluster
121   Error in eval(expr, envir, enclos): objet 'hqw...        0
1719  Error in eval(expr, envir, enclos): object 're...        0
1859                                      compile_error        0
1401  Error in eval(expr, envir, enclos): wrong resu...        0
881                                       compile_error        0
1320  Error in eval(expr, envir, enclos): object 'wm...        0
2120  Error in get(name, envir = envir): object 's_l...        0
676   Error in eval(expr, envir, enclos): object 'me...        0
1627  Error in eval(expr, envir, enclos): object '.....        0
2083  Error in eval(expr, envir, enclos): Objekt 'nu...        0


cluster 1 has 140 samples
                                                errdesc  cluster
123   Error in library("scHOT"): there is no package...        1
1063  Error in library(prophet): there is no package...        1
33    Error in library(mxnet): there is no package c...        1
147   Error in library("ggmap"): there is no package...        1
409   Error in library(tidyverse): there is no packa...        1
905   Error in library(scone): there is no package c...        1
1996  Error in library(tidyverse): there is no packa...        1
822   Error: package or namespace load failed for ‘g...        1
2040  Error in library("dummies"): there is no packa...        1
951   Error in library(geigen): there is no package ...        1


cluster 2 has 1206 samples
                                                errdesc  cluster
151                    Cannot find module 'some-module'        2
1692  Error in L(rcpitausa, 1): could not find funct...        2
206   Error in if (x$resmatrix[1] == "Error") cat("\...        2
274   Error in x%%2: argument non numérique pour un ...        2
1909  Error: Strings must match column names. Unknow...        2
864                     Direct kernel connection broken        2
1745  Error in var.test.default(low, high): not enou...        2
1964  System.ArgumentException: Column "DGdegree:Tem...        2
2175  Error in t(X) %*% beta_: non-conformable argum...        2
2149  Error in charToDate(x): character string is no...        2


cluster 3 has 72 samples
                                                errdesc  cluster
800   Error in parse(text = x, srcfile = src): <text...        3
1603  Error in parse(text = x, srcfile = src): <text...        3
1604  Error in parse(text = x, srcfile = src): <text...        3
1982  Error in parse(text = x, srcfile = src): <text...        3
1127  Error in parse(text = x, srcfile = src): <text...        3
1195  Error in parse(text = x, srcfile = src): <text...        3
1948                          ['Error in parse(text = x        3
1459  Error in parse(text = x, srcfile = src): <text...        3
817   Error in parse(text = x, srcfile = src): <text...        3
422   Error in parse(text = x, srcfile = src): <text...        3


cluster 4 has 233 samples
                                                errdesc  cluster
1540  Error in ggplot(mbta_boat, aes(x = month, y = ...        4
1776  Error in is.data.frame(x): (list) object canno...        4
1636  Error in {: task 1 failed - "Not all variable ...        4
2153  NUnit.Framework.AssertionException:   We seede...        4
1721  Error in eval(lhs, parent, parent): object 'CO...        4
1912  Error in commandArgs(trailingOnly = True): obj...        4
1650  Error in plot(genomeSizeModelDamsel): object '...        4
1613  Error in as.mcmc(OD.12C): object 'OD.12C' not ...        4
1723  Error in eval(lhs, parent, parent): object 'CO...        4
1596  Error in plot(wt, mpg, main = "Scatterplot ", ...        4


cluster 5 has 286 samples
                                                errdesc  cluster
495   OpenCV(4.5.3) C:\Users\runneradmin\AppData\Loc...        5
104   OpenCV(4.5.3) C:\Users\runneradmin\AppData\Loc...        5
2077  OpenCV(4.2.0) /Users/travis/build/skvark/openc...        5
1405  OpenCV(4.5.2) /private/var/folders/24/8k48jl6d...        5
1820  OpenCV(4.1.2) C:\projects\opencv-python\opencv...        5
1583  OpenCV(3.4.3) C:\projects\opencv-python\opencv...        5
626   OpenCV(4.1.1) /Users/travis/build/skvark/openc...        5
304   OpenCV(3.4.2) C:\Miniconda3\conda-bld\opencv-s...        5
211   (-215:Assertion failed) !_src.empty() in funct...        5
592   OpenCV(4.2.0) C:\projects\opencv-python\opencv...        5


cluster 6 has 35 samples
                               errdesc  cluster
2011  Session cannot generate requests        6
284   Session cannot generate requests        6
1798  Session cannot generate requests        6
185   Session cannot generate requests        6
161   Session cannot generate requests        6
203   Session cannot generate requests        6
1782  Session cannot generate requests        6
2092  Session cannot generate requests        6
1783  Session cannot generate requests        6
1237  Session cannot generate requests        6

## 2. Error analysis for nbs from kaggle

In [1]:
# read in all errors from the file
import pandas as pd

path_err = 'C:/Users/yirwa29/Downloads/Dataset-Nb/nbdata_k_error/nberror_k.csv'
df_err = pd.read_csv(path_err, encoding='utf-8')